# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uisrc\userSelfEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dlg_EditCurrentUserInUserDb(object):
    def setupUi(self, Dlg_EditCurrentUserInUserDb):
        Dlg_EditCurrentUserInUserDb.setObjectName("Dlg_EditCurrentUserInUserDb")
        Dlg_EditCurrentUserInUserDb.resize(400, 285)
        Dlg_EditCurrentUserInUserDb.setWindowOpacity(0.9595)
        Dlg_EditCurrentUserInUserDb.setStyleSheet("QDialog { background-color: rgb(45, 45, 45); color: white; }\n"
"\n"
"QGroupBox { font: 10pt \"Segoe UI Semibold\"; color: white; }\n"
"\n"
"QCheckBox, QLabel { font: 9pt \"Segoe UI Semilight\"; color: white; }\n"
"QCheckBox:disabled { color: gray; }\n"
"\n"
"/*  QScrollBar::vertical */\n"
"\n"
" QScrollBar:vertical\n"
" {\n"
"     background-color: #2A2929;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent #2A2929;\n"
" }\n"
"\n"
"\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color: rgb(45, 45, 45);         /* #605F5F; */\n"
"     min-height: 5px;\n"
"     border: 2px solid white;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"\n"
" QScrollBar::sub-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
" {\n"
"\n"
"     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
" {\n"
"     border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"/*  QScrollBar::horizontal */\n"
"QScrollBar:horizontal\n"
" {\n"
"     height: 15px;\n"
"     margin: 3px 15px 3px 15px;\n"
"     border: 1px transparent #2A2929;\n"
"     background-color: #2A2929;    \n"
" }\n"
"\n"
" QScrollBar::handle:horizontal\n"
" {\n"
"     background-color: rgb(45, 45, 45);      \n"
"     min-width: 5px;\n"
"     border: 2px solid white;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
" QScrollBar::add-line:horizontal\n"
" {\n"
"     margin: 0px 3px 0px 3px;\n"
"     border-image: url(./images/right_arrow_disabled.png);       \n"
"     width: 10px;\n"
"     height: 10px;\n"
"     subcontrol-position: right;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:horizontal\n"
" {\n"
"     margin: 0px 3px 0px 3px;\n"
"     border-image: url(./images/left_arrow_disabled.png);        \n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
" {\n"
"     border-image: url(./images/right_arrow.png);               \n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: right;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
" {\n"
"     border-image: url(./images/left_arrow.png);               \n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
"QComboBox {\n"
"    color: black;\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    font: 8pt \"Segoe UI Semilight\";\n"
"}\n"
"\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(254, 254, 254);\n"
"    background-color: rgb(236, 236, 236);\n"
"}\n"
"\n"
"\n"
"QPushButton { \n"
"    color: black;\n"
"    background-color: rgb(215, 215, 215);\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;  \n"
"    min-width: 6em;\n"
"    font: 8pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover { \n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"\n"
"QComboBox:disabled { color: gray; background-color: rgb(35, 35, 35); }\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/images/arrowDown_ico.png);\n"
"}\n"
"\n"
"\n"
"QComboBox::up-arrow { image: url(:/images/arrowUp_ico.png); }\n"
"\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"\n"
"QLineEdit { \n"
"    border-radius: 3px;\n"
"    border: 1px solid white;\n"
" }\n"
"\n"
"QLineEdit:hover { \n"
"    border-color: rgb(42, 105, 23);\n"
"}")
        Dlg_EditCurrentUserInUserDb.setSizeGripEnabled(False)
        Dlg_EditCurrentUserInUserDb.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dlg_EditCurrentUserInUserDb)
        self.verticalLayout.setObjectName("verticalLayout")
        self.box_MainUserProps = QtWidgets.QGroupBox(Dlg_EditCurrentUserInUserDb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_MainUserProps.sizePolicy().hasHeightForWidth())
        self.box_MainUserProps.setSizePolicy(sizePolicy)
        self.box_MainUserProps.setObjectName("box_MainUserProps")
        self.gridLayout = QtWidgets.QGridLayout(self.box_MainUserProps)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_EuLogin = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuLogin.setObjectName("lbl_EuLogin")
        self.gridLayout.addWidget(self.lbl_EuLogin, 2, 0, 1, 1)
        self.lbl_EuAvatarHint = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuAvatarHint.setObjectName("lbl_EuAvatarHint")
        self.gridLayout.addWidget(self.lbl_EuAvatarHint, 5, 0, 1, 1)
        self.lnI_EuDesc = QtWidgets.QLineEdit(self.box_MainUserProps)
        self.lnI_EuDesc.setObjectName("lnI_EuDesc")
        self.gridLayout.addWidget(self.lnI_EuDesc, 6, 1, 1, 3)
        self.lbl_EuIDHint = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuIDHint.setObjectName("lbl_EuIDHint")
        self.gridLayout.addWidget(self.lbl_EuIDHint, 1, 0, 1, 1)
        self.lbl_EuAvatarPrevHint = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuAvatarPrevHint.setObjectName("lbl_EuAvatarPrevHint")
        self.gridLayout.addWidget(self.lbl_EuAvatarPrevHint, 0, 0, 1, 1)
        self.tlb_Browse = QtWidgets.QToolButton(self.box_MainUserProps)
        self.tlb_Browse.setAutoRaise(False)
        self.tlb_Browse.setArrowType(QtCore.Qt.NoArrow)
        self.tlb_Browse.setObjectName("tlb_Browse")
        self.gridLayout.addWidget(self.tlb_Browse, 5, 3, 1, 1)
        self.lbl_EuID = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuID.setObjectName("lbl_EuID")
        self.gridLayout.addWidget(self.lbl_EuID, 1, 1, 1, 3)
        self.lnI_EuLogin = QtWidgets.QLineEdit(self.box_MainUserProps)
        self.lnI_EuLogin.setEnabled(True)
        self.lnI_EuLogin.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.lnI_EuLogin.setReadOnly(True)
        self.lnI_EuLogin.setObjectName("lnI_EuLogin")
        self.gridLayout.addWidget(self.lnI_EuLogin, 2, 1, 1, 3)
        self.gfv_EuAvatarPrev = QtWidgets.QLabel(self.box_MainUserProps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gfv_EuAvatarPrev.sizePolicy().hasHeightForWidth())
        self.gfv_EuAvatarPrev.setSizePolicy(sizePolicy)
        self.gfv_EuAvatarPrev.setMinimumSize(QtCore.QSize(80, 80))
        self.gfv_EuAvatarPrev.setMaximumSize(QtCore.QSize(80, 80))
        self.gfv_EuAvatarPrev.setStyleSheet("border: 1px solid grey;")
        self.gfv_EuAvatarPrev.setText("")
        self.gfv_EuAvatarPrev.setScaledContents(True)
        self.gfv_EuAvatarPrev.setObjectName("gfv_EuAvatarPrev")
        self.gridLayout.addWidget(self.gfv_EuAvatarPrev, 0, 1, 1, 1)
        self.lnI_EuAvatarAddr = QtWidgets.QLineEdit(self.box_MainUserProps)
        self.lnI_EuAvatarAddr.setObjectName("lnI_EuAvatarAddr")
        self.gridLayout.addWidget(self.lnI_EuAvatarAddr, 5, 1, 1, 1)
        self.lnI_EuPassword = QtWidgets.QLineEdit(self.box_MainUserProps)
        self.lnI_EuPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnI_EuPassword.setObjectName("lnI_EuPassword")
        self.gridLayout.addWidget(self.lnI_EuPassword, 4, 1, 1, 3)
        self.lbl_EuDescHint = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuDescHint.setObjectName("lbl_EuDescHint")
        self.gridLayout.addWidget(self.lbl_EuDescHint, 6, 0, 1, 1)
        self.lbl_EuPassword = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuPassword.setObjectName("lbl_EuPassword")
        self.gridLayout.addWidget(self.lbl_EuPassword, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.box_MainUserProps)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_Accept = QtWidgets.QPushButton(Dlg_EditCurrentUserInUserDb)
        self.btn_Accept.setMinimumSize(QtCore.QSize(80, 24))
        self.btn_Accept.setObjectName("btn_Accept")
        self.horizontalLayout_3.addWidget(self.btn_Accept)
        self.btn_Decline = QtWidgets.QPushButton(Dlg_EditCurrentUserInUserDb)
        self.btn_Decline.setMinimumSize(QtCore.QSize(80, 24))
        self.btn_Decline.setObjectName("btn_Decline")
        self.horizontalLayout_3.addWidget(self.btn_Decline)
        spacerItem1 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dlg_EditCurrentUserInUserDb)
        self.btn_Accept.clicked.connect(Dlg_EditCurrentUserInUserDb.accept)
        self.btn_Decline.clicked.connect(Dlg_EditCurrentUserInUserDb.reject)
        QtCore.QMetaObject.connectSlotsByName(Dlg_EditCurrentUserInUserDb)
        Dlg_EditCurrentUserInUserDb.setTabOrder(self.lnI_EuLogin, self.lnI_EuPassword)
        Dlg_EditCurrentUserInUserDb.setTabOrder(self.lnI_EuPassword, self.lnI_EuAvatarAddr)
        Dlg_EditCurrentUserInUserDb.setTabOrder(self.lnI_EuAvatarAddr, self.tlb_Browse)
        Dlg_EditCurrentUserInUserDb.setTabOrder(self.tlb_Browse, self.lnI_EuDesc)

    def retranslateUi(self, Dlg_EditCurrentUserInUserDb):
        _translate = QtCore.QCoreApplication.translate
        Dlg_EditCurrentUserInUserDb.setWindowTitle(_translate("Dlg_EditCurrentUserInUserDb", "Редактировать существующего пользователя"))
        self.box_MainUserProps.setTitle(_translate("Dlg_EditCurrentUserInUserDb", "Основные настройки"))
        self.lbl_EuLogin.setText(_translate("Dlg_EditCurrentUserInUserDb", "Логин:"))
        self.lbl_EuAvatarHint.setText(_translate("Dlg_EditCurrentUserInUserDb", "Аватарка:"))
        self.lbl_EuIDHint.setText(_translate("Dlg_EditCurrentUserInUserDb", "ID:"))
        self.lbl_EuAvatarPrevHint.setText(_translate("Dlg_EditCurrentUserInUserDb", "Просмотр:"))
        self.tlb_Browse.setText(_translate("Dlg_EditCurrentUserInUserDb", "..."))
        self.lbl_EuID.setText(_translate("Dlg_EditCurrentUserInUserDb", "(id)"))
        self.lnI_EuLogin.setToolTip(_translate("Dlg_EditCurrentUserInUserDb", "Вы не можете редактировать логин существующего пользователя"))
        self.lbl_EuDescHint.setText(_translate("Dlg_EditCurrentUserInUserDb", "Описание:"))
        self.lbl_EuPassword.setText(_translate("Dlg_EditCurrentUserInUserDb", "Пароль:"))
        self.btn_Accept.setText(_translate("Dlg_EditCurrentUserInUserDb", "Сохранить"))
        self.btn_Decline.setText(_translate("Dlg_EditCurrentUserInUserDb", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dlg_EditCurrentUserInUserDb = QtWidgets.QDialog()
    ui = Ui_Dlg_EditCurrentUserInUserDb()
    ui.setupUi(Dlg_EditCurrentUserInUserDb)
    Dlg_EditCurrentUserInUserDb.show()
    sys.exit(app.exec_())
