# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dlg_EditUserInUserDb(object):
    def setupUi(self, Dlg_EditUserInUserDb):
        Dlg_EditUserInUserDb.setObjectName("Dlg_EditUserInUserDb")
        Dlg_EditUserInUserDb.resize(401, 479)
        Dlg_EditUserInUserDb.setWindowOpacity(0.9595)
        Dlg_EditUserInUserDb.setStyleSheet("QDialog { background-color: rgb(45, 45, 45); color: white; }\n"
"\n"
"QGroupBox { font: 10pt \"Segoe UI Semibold\"; color: white; }\n"
"\n"
"QCheckBox, QLabel { font: 9pt \"Segoe UI Semilight\"; color: white; }\n"
"QCheckBox:disabled { color: gray; }\n"
"\n"
"\n"
" QScrollBar:vertical\n"
" {\n"
"     background-color: #2A2929;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent #2A2929;\n"
" }\n"
"\n"
"\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color: rgb(45, 45, 45);         /* #605F5F; */\n"
"     min-height: 5px;\n"
"     border: 2px solid white;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"\n"
" QScrollBar::sub-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
" {\n"
"\n"
"     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
" {\n"
"     border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
"QComboBox {\n"
"    color: black;\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    font: 8pt \"Segoe UI Semilight\";\n"
"}\n"
"\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(254, 254, 254);\n"
"    background-color: rgb(236, 236, 236);\n"
"}\n"
"\n"
"\n"
"QPushButton { \n"
"    color: black;\n"
"    background-color: rgb(215, 215, 215);\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;  \n"
"    min-width: 6em;\n"
"    font: 8pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover { \n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"\n"
"QComboBox:disabled { color: gray; background-color: rgb(35, 35, 35); }\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/images/arrowDown_ico.png);\n"
"}\n"
"\n"
"\n"
"QComboBox::up-arrow { image: url(:/images/arrowUp_ico.png); }\n"
"\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"\n"
"QLineEdit { \n"
"    border-radius: 3px;\n"
"    border: 1px solid white;\n"
" }\n"
"\n"
"QLineEdit:hover { \n"
"    border-color: rgb(42, 105, 23);\n"
"}")
        Dlg_EditUserInUserDb.setSizeGripEnabled(False)
        Dlg_EditUserInUserDb.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dlg_EditUserInUserDb)
        self.verticalLayout.setObjectName("verticalLayout")
        self.box_MainUserProps = QtWidgets.QGroupBox(Dlg_EditUserInUserDb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_MainUserProps.sizePolicy().hasHeightForWidth())
        self.box_MainUserProps.setSizePolicy(sizePolicy)
        self.box_MainUserProps.setObjectName("box_MainUserProps")
        self.gridLayout = QtWidgets.QGridLayout(self.box_MainUserProps)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_EuID = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuID.setObjectName("lbl_EuID")
        self.gridLayout.addWidget(self.lbl_EuID, 2, 1, 1, 3)
        self.gfv_EuAvatarPrev = QtWidgets.QLabel(self.box_MainUserProps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gfv_EuAvatarPrev.sizePolicy().hasHeightForWidth())
        self.gfv_EuAvatarPrev.setSizePolicy(sizePolicy)
        self.gfv_EuAvatarPrev.setMinimumSize(QtCore.QSize(64, 64))
        self.gfv_EuAvatarPrev.setMaximumSize(QtCore.QSize(64, 64))
        self.gfv_EuAvatarPrev.setStyleSheet("border: 1px solid grey;")
        self.gfv_EuAvatarPrev.setText("")
        self.gfv_EuAvatarPrev.setScaledContents(True)
        self.gfv_EuAvatarPrev.setObjectName("gfv_EuAvatarPrev")
        self.gridLayout.addWidget(self.gfv_EuAvatarPrev, 0, 1, 1, 1)
        self.lbl_EuDescHint = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuDescHint.setObjectName("lbl_EuDescHint")
        self.gridLayout.addWidget(self.lbl_EuDescHint, 7, 0, 1, 1)
        self.lbl_EuAvatarPrevHint = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuAvatarPrevHint.setObjectName("lbl_EuAvatarPrevHint")
        self.gridLayout.addWidget(self.lbl_EuAvatarPrevHint, 0, 0, 1, 1)
        self.lbl_EuPassword = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuPassword.setObjectName("lbl_EuPassword")
        self.gridLayout.addWidget(self.lbl_EuPassword, 5, 0, 1, 1)
        self.lnI_EuPassword = QtWidgets.QLineEdit(self.box_MainUserProps)
        self.lnI_EuPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnI_EuPassword.setObjectName("lnI_EuPassword")
        self.gridLayout.addWidget(self.lnI_EuPassword, 5, 1, 1, 3)
        self.lnI_EuDesc = QtWidgets.QLineEdit(self.box_MainUserProps)
        self.lnI_EuDesc.setObjectName("lnI_EuDesc")
        self.gridLayout.addWidget(self.lnI_EuDesc, 7, 1, 1, 3)
        self.lnI_EuAvatarAddr = QtWidgets.QLineEdit(self.box_MainUserProps)
        self.lnI_EuAvatarAddr.setObjectName("lnI_EuAvatarAddr")
        self.gridLayout.addWidget(self.lnI_EuAvatarAddr, 6, 1, 1, 1)
        self.lbl_EuIDHint = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuIDHint.setObjectName("lbl_EuIDHint")
        self.gridLayout.addWidget(self.lbl_EuIDHint, 2, 0, 1, 1)
        self.lbl_EuLogin = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuLogin.setObjectName("lbl_EuLogin")
        self.gridLayout.addWidget(self.lbl_EuLogin, 3, 0, 1, 1)
        self.lnI_EuLogin = QtWidgets.QLineEdit(self.box_MainUserProps)
        self.lnI_EuLogin.setEnabled(True)
        self.lnI_EuLogin.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.lnI_EuLogin.setReadOnly(True)
        self.lnI_EuLogin.setObjectName("lnI_EuLogin")
        self.gridLayout.addWidget(self.lnI_EuLogin, 3, 1, 1, 3)
        self.tlb_Browse = QtWidgets.QToolButton(self.box_MainUserProps)
        self.tlb_Browse.setAutoRaise(False)
        self.tlb_Browse.setArrowType(QtCore.Qt.NoArrow)
        self.tlb_Browse.setObjectName("tlb_Browse")
        self.gridLayout.addWidget(self.tlb_Browse, 6, 3, 1, 1)
        self.lbl_EuAvatarHint = QtWidgets.QLabel(self.box_MainUserProps)
        self.lbl_EuAvatarHint.setObjectName("lbl_EuAvatarHint")
        self.gridLayout.addWidget(self.lbl_EuAvatarHint, 6, 0, 1, 1)
        self.btn_EuAvatarPrevRef = QtWidgets.QPushButton(self.box_MainUserProps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_EuAvatarPrevRef.sizePolicy().hasHeightForWidth())
        self.btn_EuAvatarPrevRef.setSizePolicy(sizePolicy)
        self.btn_EuAvatarPrevRef.setMinimumSize(QtCore.QSize(64, 18))
        self.btn_EuAvatarPrevRef.setMaximumSize(QtCore.QSize(64, 18))
        self.btn_EuAvatarPrevRef.setObjectName("btn_EuAvatarPrevRef")
        self.gridLayout.addWidget(self.btn_EuAvatarPrevRef, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.box_MainUserProps)
        self.box_UserPermits = QtWidgets.QGroupBox(Dlg_EditUserInUserDb)
        self.box_UserPermits.setObjectName("box_UserPermits")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.box_UserPermits)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbb_UserPermit_4 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_4.setChecked(True)
        self.cbb_UserPermit_4.setObjectName("cbb_UserPermit_4")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_4, 7, 0, 1, 1)
        self.cbb_UserPermit_2 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_2.setObjectName("cbb_UserPermit_2")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_2, 1, 0, 1, 1)
        self.cbb_UserPermit_6 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_6.setObjectName("cbb_UserPermit_6")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_6, 0, 1, 1, 1)
        self.cbb_UserPermit_7 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_7.setEnabled(False)
        self.cbb_UserPermit_7.setObjectName("cbb_UserPermit_7")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_7, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.box_UserPermits)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 2)
        self.cbb_UserPermit_1 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_1.setEnabled(False)
        self.cbb_UserPermit_1.setCheckable(True)
        self.cbb_UserPermit_1.setChecked(True)
        self.cbb_UserPermit_1.setObjectName("cbb_UserPermit_1")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_1, 0, 0, 1, 1)
        self.cbb_UserPermit_3 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_3.setObjectName("cbb_UserPermit_3")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_3, 4, 0, 1, 1)
        self.cbb_UserPermit_8 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_8.setEnabled(False)
        self.cbb_UserPermit_8.setObjectName("cbb_UserPermit_8")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_8, 4, 1, 1, 1)
        self.cbb_UserPermit_9 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_9.setChecked(True)
        self.cbb_UserPermit_9.setObjectName("cbb_UserPermit_9")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_9, 7, 1, 1, 1)
        self.cbb_UserPermit_5 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_5.setObjectName("cbb_UserPermit_5")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_5, 8, 0, 1, 1)
        self.cbb_UserPermit_10 = QtWidgets.QCheckBox(self.box_UserPermits)
        self.cbb_UserPermit_10.setObjectName("cbb_UserPermit_10")
        self.gridLayout_2.addWidget(self.cbb_UserPermit_10, 8, 1, 1, 1)
        self.verticalLayout.addWidget(self.box_UserPermits)
        self.btb_Buttons = QtWidgets.QDialogButtonBox(Dlg_EditUserInUserDb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btb_Buttons.sizePolicy().hasHeightForWidth())
        self.btb_Buttons.setSizePolicy(sizePolicy)
        self.btb_Buttons.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btb_Buttons.setStyleSheet("min-height: 24px;")
        self.btb_Buttons.setOrientation(QtCore.Qt.Horizontal)
        self.btb_Buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.btb_Buttons.setCenterButtons(True)
        self.btb_Buttons.setObjectName("btb_Buttons")
        self.verticalLayout.addWidget(self.btb_Buttons)

        self.retranslateUi(Dlg_EditUserInUserDb)
        self.btb_Buttons.accepted.connect(Dlg_EditUserInUserDb.accept)
        self.btb_Buttons.rejected.connect(Dlg_EditUserInUserDb.reject)
        self.cbb_UserPermit_1.toggled['bool'].connect(self.cbb_UserPermit_2.setEnabled)
        self.cbb_UserPermit_6.toggled['bool'].connect(self.cbb_UserPermit_7.setEnabled)
        self.cbb_UserPermit_6.toggled['bool'].connect(self.cbb_UserPermit_8.setEnabled)
        self.cbb_UserPermit_4.toggled['bool'].connect(self.cbb_UserPermit_5.setEnabled)
        self.cbb_UserPermit_9.toggled['bool'].connect(self.cbb_UserPermit_10.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dlg_EditUserInUserDb)
        Dlg_EditUserInUserDb.setTabOrder(self.btn_EuAvatarPrevRef, self.lnI_EuLogin)
        Dlg_EditUserInUserDb.setTabOrder(self.lnI_EuLogin, self.lnI_EuPassword)
        Dlg_EditUserInUserDb.setTabOrder(self.lnI_EuPassword, self.lnI_EuAvatarAddr)
        Dlg_EditUserInUserDb.setTabOrder(self.lnI_EuAvatarAddr, self.tlb_Browse)
        Dlg_EditUserInUserDb.setTabOrder(self.tlb_Browse, self.lnI_EuDesc)
        Dlg_EditUserInUserDb.setTabOrder(self.lnI_EuDesc, self.cbb_UserPermit_1)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_1, self.cbb_UserPermit_2)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_2, self.cbb_UserPermit_3)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_3, self.cbb_UserPermit_4)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_4, self.cbb_UserPermit_5)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_5, self.cbb_UserPermit_6)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_6, self.cbb_UserPermit_7)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_7, self.cbb_UserPermit_8)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_8, self.cbb_UserPermit_9)
        Dlg_EditUserInUserDb.setTabOrder(self.cbb_UserPermit_9, self.cbb_UserPermit_10)

    def retranslateUi(self, Dlg_EditUserInUserDb):
        _translate = QtCore.QCoreApplication.translate
        Dlg_EditUserInUserDb.setWindowTitle(_translate("Dlg_EditUserInUserDb", "Редактировать существоющего пользователя"))
        self.box_MainUserProps.setTitle(_translate("Dlg_EditUserInUserDb", "Основные настройки"))
        self.lbl_EuID.setText(_translate("Dlg_EditUserInUserDb", "(id)"))
        self.lbl_EuDescHint.setText(_translate("Dlg_EditUserInUserDb", "Описание:"))
        self.lbl_EuAvatarPrevHint.setText(_translate("Dlg_EditUserInUserDb", "Просмотр:"))
        self.lbl_EuPassword.setText(_translate("Dlg_EditUserInUserDb", "Пароль:"))
        self.lbl_EuIDHint.setText(_translate("Dlg_EditUserInUserDb", "ID:"))
        self.lbl_EuLogin.setText(_translate("Dlg_EditUserInUserDb", "Логин:"))
        self.lnI_EuLogin.setToolTip(_translate("Dlg_EditUserInUserDb", "Вы не можете редактировать логин существующего пользователя"))
        self.tlb_Browse.setText(_translate("Dlg_EditUserInUserDb", "..."))
        self.lbl_EuAvatarHint.setText(_translate("Dlg_EditUserInUserDb", "Аватарка:"))
        self.btn_EuAvatarPrevRef.setText(_translate("Dlg_EditUserInUserDb", "Обновить"))
        self.box_UserPermits.setTitle(_translate("Dlg_EditUserInUserDb", "Настройки разрешений"))
        self.cbb_UserPermit_4.setText(_translate("Dlg_EditUserInUserDb", "Экран \"Оборудование\""))
        self.cbb_UserPermit_2.setText(_translate("Dlg_EditUserInUserDb", "Управление комнатами"))
        self.cbb_UserPermit_6.setText(_translate("Dlg_EditUserInUserDb", "Защита"))
        self.cbb_UserPermit_7.setText(_translate("Dlg_EditUserInUserDb", "Изменение БД защиты"))
        self.cbb_UserPermit_1.setToolTip(_translate("Dlg_EditUserInUserDb", "Отключить возможность открытия экрана статистики дома нельзя, так как это - базовая функциональность"))
        self.cbb_UserPermit_1.setText(_translate("Dlg_EditUserInUserDb", "Экран \"Статистика дома\""))
        self.cbb_UserPermit_3.setText(_translate("Dlg_EditUserInUserDb", "Экран \"Растения\""))
        self.cbb_UserPermit_8.setText(_translate("Dlg_EditUserInUserDb", "Управление системой защиты"))
        self.cbb_UserPermit_9.setText(_translate("Dlg_EditUserInUserDb", "Экран \"Конфигурация\""))
        self.cbb_UserPermit_5.setText(_translate("Dlg_EditUserInUserDb", "Доб/удл. оборудование"))
        self.cbb_UserPermit_10.setText(_translate("Dlg_EditUserInUserDb", "Настройки суперадмина"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dlg_EditUserInUserDb = QtWidgets.QDialog()
    ui = Ui_Dlg_EditUserInUserDb()
    ui.setupUi(Dlg_EditUserInUserDb)
    Dlg_EditUserInUserDb.show()
    sys.exit(app.exec_())
